name: Build AI-Thinker ESP32-CAM

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Install PlatformIO
        run: pip install platformio

      - name: Build AI-Thinker
        run: pio run -e esp32cam_ai_thinker

      - name: Find generated files
        run: |
          echo "=== BUILD FILES ==="
          find .pio/build/esp32cam_ai_thinker -type f -name "*.bin" -print
          echo
          echo "=== BUILD DIRECTORY ==="
          ls -lah .pio/build/esp32cam_ai_thinker

      - name: Prepare firmware
        run: |
          mkdir -p release

          cp .pio/build/esp32cam_ai_thinker/firmware.bin \
             release/firmware.bin

          find .pio/build/esp32cam_ai_thinker \
            -type f -name "*.bin" \
            ! -name "firmware.bin" \
            -exec cp {} release/ \;

          echo
          echo "=== FILES FOR DOWNLOAD ==="
          ls -lh release/

      - name: Upload firmware
        uses: actions/upload-artifact@v6
        with:
          name: esp32cam_ai_thinker
          path: release/
